import * as fs from "fs";
import * as path from "path";

/**
 * Marker line placed in every generated hook script. Used to
 * distinguish repo-graph-generated hooks from hand-rolled ones so
 * `installHooks` can warn (instead of silently overwriting) when
 * replacing non-repo-graph content.
 */
export const HOOK_MARKER = "# Generated by repo-graph";

export interface InstallHooksOptions {
  /** Path to .git directory. Defaults to ".git" relative to cwd. */
  gitDir?: string;
  /** Force overwrite even if existing non-repo-graph content is detected. */
  force?: boolean;
}

export interface InstallHooksResult {
  preCommitPath: string;
  postCheckoutPath: string;
  preCommitOverwritten: boolean;
  postCheckoutOverwritten: boolean;
  warned: string[];
  /** Hook names that were freshly created (did not exist before this call). */
  created: string[];
  /** Hook names that existed before this call (overwritten in place). */
  overwritten: string[];
  /** Warning messages emitted during install (e.g. for non-repo-graph content). */
  warnings: string[];
}

const PRE_COMMIT_CONTENT =
  "#!/bin/sh\n" +
  HOOK_MARKER + "\n" +
  "repo-graph update graph.db $(git diff --cached --name-only --diff-filter=ACM)\n";

const POST_CHECKOUT_CONTENT =
  "#!/bin/sh\n" +
  HOOK_MARKER + "\n" +
  "repo-graph update graph.db $(git diff --name-only \"$1\" \"$2\")\n";

/**
 * Install repo-graph git hooks into `.git/hooks/`.
 *
 * Generates POSIX-compliant shell scripts (`/bin/sh`, no bashisms):
 *   - `pre-commit` runs `repo-graph update graph.db` against the staged file list
 *   - `post-checkout` runs `repo-graph update graph.db` against the changed files
 *
 * Idempotent: re-running overwrites previous repo-graph hooks silently.
 * If a hook file already exists with non-repo-graph content, the function
 * emits a warning and saves a `.bak` copy unless `force: true` is set.
 *
 * @param gitDirOrOptions - Either a path string (legacy positional form) or an options object.
 * @param legacyOptions - When first arg is a string, second arg may provide options.
 */
export async function installHooks(
  gitDirOrOptions?: string | InstallHooksOptions,
  legacyOptions?: InstallHooksOptions
): Promise<InstallHooksResult> {
  // Resolve arguments: support both `installHooks(gitDir)` and `installHooks({ gitDir, force })`.
  let gitDir: string;
  let options: InstallHooksOptions;
  if (typeof gitDirOrOptions === "string" || gitDirOrOptions === undefined) {
    gitDir = gitDirOrOptions ?? path.join(process.cwd(), ".git");
    options = legacyOptions ?? {};
  } else {
    gitDir = gitDirOrOptions.gitDir ?? path.join(process.cwd(), ".git");
    options = gitDirOrOptions;
  }
  const force = options.force ?? false;

  // Path-traversal guard: reject gitDir containing `..` segments that would
  // cause path.join(gitDir, "hooks") to escape the intended git directory.
  // path.join normalizes `..` segments away (e.g. "foo/../../etc" becomes "/etc"),
  // so we check the raw string for `..` components before normalization.
  if (gitDir.split(path.sep).includes("..")) {
    throw new Error(
      `Path traversal rejected: gitDir must not contain ".." segments. ` +
      `Got "${gitDir}".`
    );
  }

  const hooksDir = path.join(gitDir, "hooks");
  fs.mkdirSync(hooksDir, { recursive: true });

  const preCommitPath = path.join(hooksDir, "pre-commit");
  const postCheckoutPath = path.join(hooksDir, "post-checkout");

  const result: InstallHooksResult = {
    preCommitPath,
    postCheckoutPath,
    preCommitOverwritten: false,
    postCheckoutOverwritten: false,
    warned: [],
    created: [],
    overwritten: [],
    warnings: [],
  };

  writeHook(preCommitPath, PRE_COMMIT_CONTENT, "pre-commit", force, result);
  writeHook(postCheckoutPath, POST_CHECKOUT_CONTENT, "post-checkout", force, result);

  return result;
}

/**
 * Write a single hook file. Detects existing content and either:
 *   - silently overwrites a repo-graph hook (idempotent re-run)
 *   - warns and backs up non-repo-graph content (unless force=true)
 *   - creates a new file when none existed before
 *
 * Uses a temp-file + rename pattern for atomic writes: the hook script
 * is first written to a `.tmp` file, then atomically renamed over the
 * target. This prevents partial-write corruption if the process is
 * interrupted mid-write.
 */
function writeHook(
  hookPath: string,
  content: string,
  hookName: string,
  force: boolean,
  result: InstallHooksResult
): void {
  if (fs.existsSync(hookPath)) {
    let existing = "";
    try {
      existing = fs.readFileSync(hookPath, "utf-8");
    } catch {
      existing = "";
    }

    const isRepoGraphHook = existing.includes(HOOK_MARKER);
    if (!isRepoGraphHook && !force) {
      const message = `Overwriting existing hook at ${hookPath} (saved as ${hookPath}.bak)`;
      console.warn(message);
      result.warned.push(message);
      result.warnings.push(message);
      try {
        fs.copyFileSync(hookPath, hookPath + ".bak");
      } catch {
        // backup failure is non-fatal
      }
    }

    // Atomic write: temp file + rename
    const tmpPath = hookPath + ".tmp." + process.pid;
    try {
      fs.writeFileSync(tmpPath, content);
      fs.renameSync(tmpPath, hookPath);
    } catch {
      // Fallback: direct write if rename fails (e.g. cross-device)
      fs.writeFileSync(hookPath, content);
      try { fs.unlinkSync(tmpPath); } catch { /* best-effort cleanup */ }
    }
    fs.chmodSync(hookPath, 0o755);
    if (hookName === "pre-commit") result.preCommitOverwritten = true;
    if (hookName === "post-checkout") result.postCheckoutOverwritten = true;
    result.overwritten.push(hookName);
  } else {
    // Atomic write: temp file + rename
    const tmpPath = hookPath + ".tmp." + process.pid;
    try {
      fs.writeFileSync(tmpPath, content);
      fs.renameSync(tmpPath, hookPath);
    } catch {
      // Fallback: direct write if rename fails (e.g. cross-device)
      fs.writeFileSync(hookPath, content);
      try { fs.unlinkSync(tmpPath); } catch { /* best-effort cleanup */ }
    }
    fs.chmodSync(hookPath, 0o755);
    result.created.push(hookName);
  }
}
